services:
    sonata.admin.cj_email:
        class: CreditJeeves\AdminBundle\Admin\EmailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Holdings" }
        arguments:
            - ~
            - Rj\EmailBundle\Entity\EmailTemplate
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setLocales, [%rj_email.locales%]]
            
# Admin groups for all applications
    sonata.admin.admin:
        class: CreditJeeves\AdminBundle\Admin\AdminAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Admins" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Admin
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    rj_email.email_admin:
        class: CreditJeeves\AdminBundle\Admin\EmailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Emails" }
        arguments:
            - ~
            - Rj\EmailBundle\Entity\EmailTemplate
            - 'RjEmailBundle:EmailTemplateAdmin'
        calls:
            - [ setLocales, [%rj_email.locales%]]

    sonata.admin.cj_holding:
        class: CreditJeeves\AdminBundle\Admin\CjHoldingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Holdings" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Holding
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.affiliate:
        class: CreditJeeves\AdminBundle\Admin\AffiliateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Affiliates" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Affiliate
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

#Credit jeeves application
    sonata.admin.cj_group:
        class: CreditJeeves\AdminBundle\Admin\CjGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Groups" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.lead:
        class: CreditJeeves\AdminBundle\Admin\LeadAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Leads" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Lead
            - 'SonataAdminBundle:CRUD'

    sonata.admin.dealer:
        class: CreditJeeves\AdminBundle\Admin\DealerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Dealers" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Dealer
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.applicant:
        class: CreditJeeves\AdminBundle\Admin\ApplicantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Applicants" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Applicant
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.report:
        class: CreditJeeves\AdminBundle\Admin\ReportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Reports" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Report
            - 'SonataAdminBundle:CRUD'
