services:
# Admin groups for all applications
    sonata.admin.admin:
        class: CreditJeeves\AdminBundle\Admin\AdminAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Admins" }
        arguments:
            - ~
<<<<<<< HEAD
            - CreditJeeves\DataBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
=======
            - CreditJeeves\DataBundle\Entity\Admin
            - 'AdminBundle:AdminAdmin'
>>>>>>> a565867c7e278da6faac6ec5194230980c58851e
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    rj_email.email_admin:
        class: CreditJeeves\AdminBundle\Admin\EmailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Emails" }
        arguments:
            - ~
            - Rj\EmailBundle\Entity\EmailTemplate
            - 'RjEmailBundle:EmailTemplateAdmin'
        calls:
            - [ setLocales, [%rj_email.locales%]]


#Credit jeeves application
    sonata.admin.group:
        class: CreditJeeves\AdminBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Groups" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.applicant:
        class: CreditJeeves\AdminBundle\Admin\ApplicantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Applicants" }
        arguments:
            - ~
<<<<<<< HEAD
            - CreditJeeves\DataBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
=======
            - CreditJeeves\DataBundle\Entity\Applicant
            - 'AdminBundle:ApplicantAdmin'
>>>>>>> a565867c7e278da6faac6ec5194230980c58851e
#        calls:
#            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.dealer:
        class: CreditJeeves\AdminBundle\Admin\DealerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CreditJeeves, label: "Dealers" }
        arguments:
            - ~
<<<<<<< HEAD
            - CreditJeeves\DataBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
=======
            - CreditJeeves\DataBundle\Entity\Dealer
            - 'AdminBundle:DealerAdmin'
>>>>>>> a565867c7e278da6faac6ec5194230980c58851e
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

# RentJeeves application
    sonata.admin.tenant:
        class: CreditJeeves\AdminBundle\Admin\TenantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Tenants" }
        arguments:
            - ~
<<<<<<< HEAD
            - CreditJeeves\DataBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
=======
            - CreditJeeves\DataBundle\Entity\Tenant
            - 'AdminBundle:TenantAdmin'
>>>>>>> a565867c7e278da6faac6ec5194230980c58851e
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.landlord:
        class: CreditJeeves\AdminBundle\Admin\LandlordAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Landlords" }
        arguments:
            - ~
<<<<<<< HEAD
            - CreditJeeves\DataBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
=======
            - CreditJeeves\DataBundle\Entity\Landlord
            - 'AdminBundle:LandlordAdmin'
>>>>>>> a565867c7e278da6faac6ec5194230980c58851e
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

