parameters:
#    admin.example.class: CreditJeeves\AdminBundle\Example

services:
#  creditjeeves.admin.group:
#        class: CreditJeeves\AdminBundle\GroupAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: admin, label: group }
#        arguments: [null, CreditJeeves\DataBundle\Entity\Group, SonataAdminBundle:CRUD]

#    admin.example:
#        class: %admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
