parameters:
    payment_account.class: RentJeeves\CheckoutBundle\Payment\PaymentAccount

services:
    payment.account:
        class: "%payment_account.class%"
        calls:
            - [setPayum, ["@payum"]]
