parameters:
    payment_account.heartland.class: RentJeeves\CheckoutBundle\PaymentProcessor\Heartland\PaymentAccountManager
    payment_processor.aci.collect_pay.report_loader.class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\ReportLoader
    payment_processor.aci.pay_anyone.report_loader.class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\ReportLoader
    payment.charge_heartland.class: RentJeeves\CheckoutBundle\PaymentProcessor\Heartland\ChargeHeartland
    payment.pay_heartland: RentJeeves\CheckoutBundle\PaymentProcessor\Heartland\PayHeartland

services:
    payment.account.heartland:
        class: "%payment_account.heartland.class%"
        calls:
            - [setPayum, ["@payum2"]]
            - [setDefaultMerchantName, ["%rt_merchant_name%"]]

    payment_processor.aci.pgp_decoder:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\Encoder\AciPgpDecoder
        public: false
        arguments:
            - %aci.pgp_key_path%

    payment.charge_heartland:
        class: "%payment.charge_heartland.class%"
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @payum2
            - @payment.heartland.payment_details_mapper
            - "%rt_merchant_name%"

    payment.pay_heartland:
        class: "%payment.pay_heartland%"
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @payum2
            - @payment.heartland.payment_details_mapper
            - "%rt_merchant_name%"

    # ACI collect pay
    payment_processor.aci.collect_pay.report_loader:
        class: %payment_processor.aci.collect_pay.report_loader.class%
        public: false
        arguments:
            - @payment_processor.aci.collect_pay.files_downloader
            - @payment_processor.aci.pgp_decoder
            - @payment_processor.aci.collect_pay.report_archiver
            - @payment_processor.aci.collect_pay.lockbox_parser
            - @logger

    payment_processor.aci.collect_pay.files_downloader:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\Downloader\AciSftpFilesDownloader
        public: false
        arguments:
            - %aci.collect_pay.sftp.host%
            - %aci.collect_pay.sftp.port%
            - %aci.collect_pay.sftp.login%
            - %aci.collect_pay.sftp.password%
            - %aci.collect_pay.report_path%
            - @logger
            - @sftp_client

    payment_processor.aci.collect_pay.lockbox_parser:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\Report\LockboxParser
        public: false
        arguments:
            - @logger

    payment_processor.aci.collect_pay.report_archiver:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\AciReportArchiver
        public: false
        arguments:
            - %aci.collect_pay.report_path%
            - @logger

    payment_processor.aci.collect_pay.billing_account_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\BillingAccountManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger

    payment_processor.aci.collect_pay.enrollment_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\EnrollmentManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger
        calls:
            - [setDefaultBusinessId, ["%aci.collect_pay.business_id%"]]

    payment_processor.aci.collect_pay.funding_account_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\FundingAccountManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger

    payment_processor.aci.collect_pay.payment_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\PaymentManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger
        calls:
            - [setDefaultBusinessId, ["%aci.collect_pay.business_id%"]]

    payment_processor.aci.pay_anyone.report_loader:
        class: %payment_processor.aci.pay_anyone.report_loader.class%
        public: false
        arguments:
            - @payment_processor.aci.pay_anyone.files_downloader
            - @payment_processor.aci.pgp_decoder
            - @payment_processor.aci.pay_anyone.report_archiver
            - @payment_processor.aci.pay_anyone.response_parser
            - @payment_processor.aci.pay_anyone.adjustment_parser
            - @logger

    payment_processor.aci.pay_anyone.files_downloader:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\Downloader\AciSftpFilesDownloader
        public: false
        arguments:
            - %aci.pay_anyone.sftp.host%
            - %aci.pay_anyone.sftp.port%
            - %aci.pay_anyone.sftp.login%
            - %aci.pay_anyone.sftp.password%
            - %aci.pay_anyone.report_path%
            - @logger
            - @sftp_client

    payment_processor.aci.pay_anyone.adjustment_parser:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\Parser\AdjustmentParser
        public: false
        arguments:
            - @serializer
            - @logger

    payment_processor.aci.pay_anyone.response_parser:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\Parser\ResponseParser
        public: false
        arguments:
            - @serializer
            - @logger

    payment_processor.aci.pay_anyone.report_archiver:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\AciReportArchiver
        public: false
        arguments:
            - %aci.pay_anyone.report_path%
            - @logger
