parameters:
    payment_account.heartland.class: RentJeeves\CheckoutBundle\PaymentProcessor\Heartland\PaymentAccountManager

services:
    payment.account.heartland:
        class: "%payment_account.heartland.class%"
        calls:
            - [setPayum, ["@payum2"]]
