parameters:
    payment_account.heartland.class: RentJeeves\CheckoutBundle\PaymentProcessor\Heartland\PaymentAccountManager
    payment_processor.aci.collect_pay.report_loader.class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\ReportLoader
    payment_processor.aci.pay_anyone.report_loader.class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\ReportLoader
    payment.charge_heartland.class: RentJeeves\CheckoutBundle\PaymentProcessor\Heartland\ChargeHeartland
    payment.pay_heartland: RentJeeves\CheckoutBundle\PaymentProcessor\Heartland\PayHeartland
    payment_processor.aci.pay_anyone.check_sender.class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\CheckSender

services:
    payment.terminal:
        class: RentJeeves\CheckoutBundle\Payment\Terminal
        arguments:
            - @payment_processor.order_creation_manager
            - @payment_processor.order_status_manager
            - @doctrine.orm.default_entity_manager
            - @logger
        calls:
            - [setFactory, ["@payment_processor.factory"]]

    payment.pay_rent:
        class: RentJeeves\CheckoutBundle\Payment\PayRent
        arguments:
            - @payment_processor.order_creation_manager
            - @payment_processor.order_status_manager
            - @doctrine.orm.default_entity_manager
            - @logger
        calls:
            - [setFactory, ["@payment_processor.factory"]]

    payment.pay_credit_track:
        class: RentJeeves\CheckoutBundle\Payment\PayCreditTrack
        arguments:
            - @payment_processor.order_creation_manager
            - @payment_processor.order_status_manager
            - @doctrine.orm.default_entity_manager
            - @credit_summary.report_builder_factory
            - %credit_summary_vendor%
        calls:
            - [setFactory, ["@payment_processor.factory"]]

    payment.account.heartland:
        class: "%payment_account.heartland.class%"
        arguments:
            - @doctrine.orm.default_entity_manager
            - @payum2
            - %rt_group_code%

    payment_processor.report_synchronizer:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Report\ReportSynchronizer
        arguments:
            - @doctrine.orm.default_entity_manager
            - @logger
            - @payment_processor.order_status_manager

    payment_processor.aci.pgp_decoder:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\Encoder\AciPgpDecoder
        public: false
        arguments:
            - %aci.pgp_key_path%

    payment.charge_heartland:
        class: "%payment.charge_heartland.class%"
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @payum2
            - @payment.heartland.payment_details_mapper

    payment.pay_heartland:
        class: "%payment.pay_heartland%"
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @payum2
            - @payment.heartland.payment_details_mapper

    # ACI collect pay
    payment_processor.aci.collect_pay.report_loader:
        class: %payment_processor.aci.collect_pay.report_loader.class%
        public: false
        arguments:
            - @payment_processor.aci.collect_pay.files_downloader
            - @payment_processor.aci.pgp_decoder
            - @payment_processor.aci.collect_pay.report_archiver
            - @payment_processor.aci.collect_pay.lockbox_parser
            - @logger

    payment_processor.aci.collect_pay.files_downloader:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\Downloader\AciSftpFilesDownloader
        public: false
        arguments:
            - %aci.collect_pay.sftp.host%
            - %aci.collect_pay.sftp.port%
            - %aci.collect_pay.sftp.login%
            - %aci.collect_pay.sftp.password%
            - %aci.collect_pay.report_path%
            - @logger
            - @sftp_client

    payment_processor.aci.collect_pay.lockbox_parser:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\Report\LockboxParser
        public: false
        arguments:
            - @logger

    payment_processor.aci.collect_pay.report_archiver:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\AciReportArchiver
        public: false
        arguments:
            - %aci.collect_pay.report_path%
            - @logger

    payment_processor.aci.collect_pay.billing_account_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\BillingAccountManager
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger

    payment_processor.aci.collect_pay.enrollment_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\EnrollmentManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger
        calls:
            - [setVirtualTerminalBusinessId, ["%aci.collect_pay.renttrack_virtual_terminal_account%"]]

    payment_processor.aci.collect_pay.funding_account_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\FundingAccountManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger

    payment_processor.aci.collect_pay.payment_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\PaymentManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger
        calls:
            - [setVirtualTerminalBusinessId, ["%aci.collect_pay.renttrack_virtual_terminal_account%"]]

    payment_processor.aci.collect_pay.lcr_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\CollectPay\LeastCostRouteManager
        public: false
        arguments:
            - @payum
            - @logger

    payment_processor.aci.pay_anyone.payment_manager:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\PaymentManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @payum
            - @logger
        calls:
            - [setConfig, ["%aci.pay_anyone.default_achAccount%"]]

    payment_processor.aci.pay_anyone.report_loader:
        class: %payment_processor.aci.pay_anyone.report_loader.class%
        public: false
        arguments:
            - @payment_processor.aci.pay_anyone.files_downloader
            - @payment_processor.aci.pgp_decoder
            - @payment_processor.aci.pay_anyone.report_archiver
            - @payment_processor.aci.pay_anyone.response_parser
            - @payment_processor.aci.pay_anyone.adjustment_parser
            - @logger

    payment_processor.aci.pay_anyone.files_downloader:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\Downloader\AciSftpFilesDownloader
        public: false
        arguments:
            - %aci.pay_anyone.sftp.host%
            - %aci.pay_anyone.sftp.port%
            - %aci.pay_anyone.sftp.login%
            - %aci.pay_anyone.sftp.password%
            - %aci.pay_anyone.report_path%
            - @logger
            - @sftp_client

    payment_processor.aci.pay_anyone.adjustment_parser:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\Parser\AdjustmentParser
        public: false
        arguments:
            - @serializer
            - @logger

    payment_processor.aci.pay_anyone.response_parser:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\PayAnyone\Parser\ResponseParser
        public: false
        arguments:
            - @serializer
            - @logger

    payment_processor.aci.pay_anyone.report_archiver:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\Aci\AciReportArchiver
        public: false
        arguments:
            - %aci.pay_anyone.report_path%
            - @logger

    payment_processor.aci.pay_anyone.check_sender:
        class: %payment_processor.aci.pay_anyone.check_sender.class%
        arguments:
            - @payment_processor.aci_pay_anyone
            - @logger

    payment_processor.order_status_manager:
        class: RentJeeves\CheckoutBundle\Payment\OrderManagement\OrderStatusManager\OrderStatusManager
        calls:
            - [setManagers, ["@payment_processor.order_status_manager.submerchant", "@payment_processor.order_status_manager.pay_direct"]]

    payment_processor.order_status_manager.submerchant:
        class: RentJeeves\CheckoutBundle\Payment\OrderManagement\OrderStatusManager\OrderSubmerchantStatusManager
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @logger
            - @project.mailer

    payment_processor.order_status_manager.pay_direct:
        class: RentJeeves\CheckoutBundle\Payment\OrderManagement\OrderStatusManager\OrderPayDirectStatusManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @logger
            - @project.mailer
            - @payment_processor.aci.pay_anyone.check_sender


    payment_processor.order_creation_manager:
        class: RentJeeves\CheckoutBundle\Payment\OrderManagement\OrderCreationManager\OrderCreationManager
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @checkout.paid_for
            - %rt_group_code%
            - %credittrack_payment_per_month%

    pidkiq.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - CreditJeeves\DataBundle\Entity\Pidkiq

    payment.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - RentJeeves\DataBundle\Entity\Payment

    order.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - CreditJeeves\DataBundle\Entity\Order

    operation.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - CreditJeeves\DataBundle\Entity\Operation

    contract.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - RentJeeves\DataBundle\Entity\Contract

    dod.payment_rolling_window_dtr:
        class: RentJeeves\CheckoutBundle\DoD\Rule\PaymentRollingWindowDTR
        arguments:
            - @order.repository
            - %dod_dtr_payment_rolling_window%

    dod.payment_first_time_dtr:
        class: RentJeeves\CheckoutBundle\DoD\Rule\PaymentFirstTimeDTR
        arguments:
            - @pidkiq.repository
            - @payment.repository
            - @order.repository

    dod.payment_sum_limit_per_month_dtr:
        class: RentJeeves\CheckoutBundle\DoD\Rule\PaymentSumLimitPerMonthDTR
        arguments:
            - @operation.repository

    dod.payment_to_trusted_landlord_dtr:
        class: RentJeeves\CheckoutBundle\DoD\Rule\PaymentToTrustedLandlordDTR
        arguments:
            - @project.mailer

    dod.payment_amount_max:
        class: RentJeeves\CheckoutBundle\DoD\Rule\PaymentAmountMaxLimit
        arguments:
            - %dod_limit_max_payment%

    dod.payment_execution_allowed:
        class: RentJeeves\CheckoutBundle\DoD\Rule\PaymentExecutionAllowed

    dod.payment_match_check_mailing_address_and_unit_address_dtr:
        class: RentJeeves\CheckoutBundle\DoD\Rule\PaymentMatchCheckMailingAddressAndUnitAddressDTR

    dod:
        class: RentJeeves\CheckoutBundle\DoD\DodManager
        arguments:
            - @logger
        calls:
            - [addRule, ["@dod.payment_to_trusted_landlord_dtr"]]
            - [addRule, ["@dod.payment_amount_max"]]
            - [addRule, ["@dod.payment_execution_allowed"]]
            - [addRule, ["@dod.payment_rolling_window_dtr"]]
            - [addRule, ["@dod.payment_first_time_dtr"]]
            - [addRule, ["@dod.payment_sum_limit_per_month_dtr"]]
            - [addRule, ["@dod.payment_to_trusted_landlord_dtr"]]
            - [addRule, ["@dod.payment_match_check_mailing_address_and_unit_address_dtr"]]

    payment_processor.profit_stars.rdc.client:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\ProfitStars\RDC\RDCClient
        arguments:
            - @profit_stars.remote_deposit_reporting.client
            - @monolog.logger.profit_stars
            - %profit_stars.store_id%
            - %profit_stars.store_key%

    payment_processor.profit_stars.rdc.report_loader:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\ProfitStars\RDC\ReportLoader
        public: false
        arguments:
            - @profit_stars.transaction_reporting.client
            - @payment_processor.profit_stars.rdc.client
            - @payment_processor.profit_stars.rdc.check_transformer
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.profit_stars
            - %profit_stars.store_id%
            - %profit_stars.store_key%

    payment_processor.profit_stars.rdc.contract_registry:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\ProfitStars\RDC\ContractRegistryManager
        public: false
        arguments:
            - @profit_stars.payment_vault.client
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.profit_stars
            - @skip32.id_encoder
            - %profit_stars.store_id%
            - %profit_stars.store_key%

    payment_processor.profit_stars.rdc.check_transformer:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\ProfitStars\RDC\ScannedCheckTransformer
        public: false
        arguments:
            - @skip32.id_encoder
            - @contract.repository
            - @monolog.logger.profit_stars

    payment_processor.profit_stars.rdc.remote_deposit_loader:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\ProfitStars\RDC\RemoteDepositLoader
        public: false
        arguments:
            - '@payment_processor.profit_stars.rdc.client'
            - '@payment_processor.profit_stars.rdc.check_transformer'
            - '@doctrine.orm.default_entity_manager'
            - '@monolog.logger.profit_stars'
            - '@renttrack.contract_manager'
            - '@accounting.payment_sync'
            - '@project.mailer'

    payment_processor.profit_stars.rdc:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\PaymentProcessorProfitStarsRdc
        arguments:
            - '@payment_processor.profit_stars.rdc.report_loader'
            - '@payment_processor.profit_stars.rdc.contract_registry'
            - '@payment_processor.profit_stars.rdc.remote_deposit_loader'

    payment_processor.profit_stars.report_synchronizer:
        class: RentJeeves\CheckoutBundle\PaymentProcessor\ProfitStars\ProfitStarsReportSynchronizer
        arguments:
            - '@profit_stars.transaction_reporting.client'
            - '@payment_processor.order_status_manager'
            - '@payment_processor.profit_stars.rdc'
            - '@doctrine.orm.default_entity_manager'
            - '@monolog.logger.profit_stars'
            - '%profit_stars.store_id%'
            - '%profit_stars.store_key%'
