parameters:
    core.experian.net_connect.class: CreditJeeves\CoreBundle\Experian\NetConnect
    core.event_listener.controller.class: CreditJeeves\CoreBundle\EventListener\Controller

services:
    core.experian.net_connect:
        class: %core.experian.net_connect.class%
        arguments: []
    core.event_listener.controller:
        class: %core.event_listener.controller.class%
        arguments:  []
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
