parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: cj_stg
    database_user: root
    database_password: 'passw0rd'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    server: stg
    server_name: stg2.creditjeeves.com

    authorize_net:
        login_id: '29fDg7sU24G'
        transaction_key: '474v43G35wJ6Gm2d'
        sandbox: false
