imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: credit_jeeves2
    database_password: 'passw0rd'

    server: dev
    server_name: cj2
    mink.selenium2.wd_host: 'http://127.0.0.1:4444/wd/hub'
