checkout:
    resource: "@CheckoutBundle/Controller/"
    type:     annotation
    prefix:   /

experian:
    resource: "@ExperianBundle/Controller/"
    type:     annotation
    prefix:   /

public:
    resource: "@PublicBundle/Controller"
    type:     annotation

core:
    resource: "@CoreBundle/Controller"
    type:     annotation

user:
    resource: "@UserBundle/Controller"
    type:     annotation

admin_common:
    resource: "@AdminBundle/Controller"
    type:     annotation
    prefix:   /admin

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

dealer:
    resource: "@DealerBundle/Controller"
    type:     annotation
    prefix:   /dealer

applicant:
    resource: "@ApplicantBundle/Controller"
    type:     annotation

landlord:
    resource: "@LandlordBundle/Controller/"
    type:     annotation
    prefix:   /landlord

tenant:
    resource: "@TenantBundle/Controller/"
    type:     annotation
    prefix:   /tenant

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_resetting_request:
    path:     /resetting
    defaults:
        _controller: FOSUserBundle:Resetting:request
        _method:     GET

#fos_user_profile_show:


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
