parameters:
    component.menu.main.class: CreditJeeves\ComponentBundle\Menu\Main

services:
    component.menu.main:
        class: %component.menu.main.class%
        arguments: [@security.context]
