parameters:
#    component.example.class: CreditJeeves\ComponentBundle\Example

services:
#    component.example:
#        class: %component.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
