services:
    address_lookup_service: @address_lookup_service.google

    address_lookup_service.google:
        class: RentJeeves\CoreBundle\Services\AddressLookup\GoogleGeocoderAddressLookupService
        arguments:
            - @bazinga_geocoder.geocoder
            - @validator
            - @logger

    address_lookup_service.smarty_streets:
        class: RentJeeves\CoreBundle\Services\AddressLookup\SmartyStreetsAddressLookupService
        arguments:
            - @smarty_streets.client
            - @validator
            - @logger

    smarty_streets.cache:
        class: RentJeeves\CoreBundle\Services\AddressLookup\Cache\SmartyStreetsCacheService
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
