# It moved here because #RT-407

parameters:
    data.event_listener.order.class: RentJeeves\DataBundle\EventListener\OrderListener

services:
    data.event_listener.order:
        class: "%data.event_listener.order.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
        arguments: ["@service_container"]
