# It moved here because #RT-407

parameters:
    data.event_listener.order.class: RentJeeves\DataBundle\EventListener\OrderListener
    data.event_listener.import_summary.class: RentJeeves\DataBundle\EventListener\ImportSummaryListener

services:
    data.event_listener.order:
        class: "%data.event_listener.order.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
        arguments:
            - "@service_container"
            - "@logger"
    data.event_listener.import_summary:
        class: "%data.event_listener.import_summary.class%"
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
        arguments:
            - "@skip32.id_encoder"
