imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: credit_jeeves2
    database_password: 'passw0rd'

    server_name_cj: dev2.creditjeeves.com
    server_name_rj: dev2.renttrack.com
    mink.selenium2.wd_host: 'http://10.46.179.1:4444/wd/hub'
