parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
  database_name: creditjeeves2
  database_user: admin
  database_password: 'qwerty'
  mailer_transport: mail
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null

