imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: credit_jeeves
    database_password: 'passw0rd'


    host: dev2.creditjeeves.com
    server_name: cj2
