parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: renttrack
    database_user: root
    database_password: 'passw0rd'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_delivery_address: null
    mailer_disable_delivery: false
    api.admin_dealer_code: 1a1dc91c9073
    api.client_id: 1_qvxzb7ge734ko4ogwcskwksogoc0wskws40gg8oocokwg404s
    api.client_secret: 39uyn651qlk4ssws40sgs44cwsskgccoc0o04ccgsccgooowwo
    server: live
    server_name_cj: my.creditjeeves.com
    server_name_rj: my.renttrack.com

    google_maps_key: 'AIzaSyBWwRKgFPdWQYzzwGKaDL83ojLxGGFvGV4' # API account with systems@renttrack.com

    session.lifetime: 900 #in seconds
    payment_processor.hps.report_path: /home/heartland
    heartland:
        application_id: 1
        username: RTAPI
        password: $RTapi13

    # aci.collect_pay.sftp.login: 'donotcheckin'      # this is set locally on server
    # aci.collect_pay.sftp.password: 'donotcheckin'   # this is set locally on server
    # aci.collect_pay.business_id: donotcheckin       # this is set locally on server
    # aci.pay_anyone.sftp.login: 'donotcheckin'       # this is set locally on server
    # aci.pay_anyone.sftp.password: 'donotcheckin'    # this is set locally on server

    net_connect.precise_id.url: 'https://ss3.experian.com/fraudsolutions/xmlgateway/preciseid' #required!
    net_connect.precise_id.dbhost: 'PRECISE_ID' #required!
    net_connect.precise_id.sub_code: '2279720' #required!
    net_connect.credit_profile.url: 'http://www.experian.com/lookupServlet1?lookupServiceName=AccessPoint&lookupServiceVersion=1.0&serviceName=NetConnect&serviceVersion=2.0&responseType=text/plain' #required!
    net_connect.credit_profile.dbhost: 'CIS' #required!
    net_connect.credit_profile.sub_code: '2266580' #required!
    net_connect.credit_profile.d2c.sub_code: '2266580' #required!

    pidkiq.lifetime.minutes: 10

    soap.api.yardi.entity: RentTrack
    soap.api.yardi.license: V100057742BP.lic
    soap.api.yardi.path_to_classes: RentJeeves\ExternalApiBundle\Services\Yardi\Soap\

    validator.translation_domain: messages

    # parameter was added for task RT-362, we can fast allow and disallow feature that disallow duplicate contract
    allow_duplicate_contracts: false
    # parameter was added for task RT-1668, we can fast allow and disallow feature that show Score Track
    allow_score_track: false

    resman.integration_partner_id: 1073
    resman.api_key: e2344f3b0fd6482c8978e0dcab3d42db
    resman.api_url: https://api.myresman.com/MITS/

    pdo.db_options:
        db_table:        session
        db_id_col:       session_id
        db_data_col:     session_value
        db_time_col:     session_time

    transunion.account_name: 'CC2RentTrack'
    # transunion.password: 'donotcheckin' # this is set locally on server
    transunion.environment: prod
    transunion.ssl_key: /var/www/my.renttrack.com/app/config/secrets/transunion/my.renttrack.com.key
    transunion.ca_certificate:  /var/www/my.renttrack.com/app/config/secrets/transunion/TUIExternalCA.pem
    transunion.ssl_certificate:  /var/www/my.renttrack.com/app/config/secrets/transunion/my.renttrack_20150114.crt
    transunion.renttrack_snapshot_bundle: 'CC2RentTrackTUReportSnapshot'
    transunion.renttrack_vantage_score_3_bundle: 'CC2RentTrackTUVantage3Score'

    monolog.email_from: systems@renttrack.com
    monolog.alert.email_to: escalations@renttrack.com
    monolog.emergency.email_to: emergency-email-alerts@renttrack.pagerduty.com

