imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: credit_jeeves2
    database_password: 'passw0rd'

    server_name_cj: dar.creditjeeves.com
    server_name_rj: dar.renttrack.com
