parameters:
    database_host: localhost
    database_driver: pdo_mysql
    database_port: null
    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    session.lifetime:  3600 #in seconds
    api.client_id: 1_qvxzb7ge734ko4ogwcskwksogoc0wskws40gg8oocokwg404s
    api.client_secret: 39uyn651qlk4ssws40sgs44cwsskgccoc0o04ccgsccgooowwo
    api.admin_dealer_code: 1a1dc91c9073
    mink.browser_name: 'firefox'
    mink.base_url: 'http://%server_name%/_test.php'
    mink.coverage_script_url: 'http://%server_name%/bundles/mink/phpunit_coverage.php'
    server: dev
    google_maps_key: 'AIzaSyAY1u4_NA6UsJa4gDfTZjmQ6-18dxxeC24'
    authorize_net:
        login_id: '7hNc5K44'
        transaction_key: '5588K4QpHFhhqL5A'
        sandbox: true
    heartland:
        env: testing
        application_id: 3
        username: RTAPI
        password: $RTapi13
    rt_merchant_name: 'RentTrack'
#    digital_signature:
    digital_signature.private_key: /home/tatyana/projects/cj/cj2/src/RentJeeves/CoreBundle/Resources/keys/saml_renttrack_com_key.txt
    digital_signature.certificate: /home/tatyana/projects/cj/cj2/src/RentJeeves/CoreBundle/Resources/keys/saml_renttrack_com_cert.txt
