imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: renttrack
    database_user: root
    database_password: 'passw0rd'

    server_name_cj: dar.creditjeeves.com
    server_name_rj: dar.renttrack.com
