parameters:
    database_host: localhost
    database_driver: pdo_mysql
    database_port: null
    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    session.lifetime:  3600 #in seconds
    mink.browser_name: 'firefox'
    mink.base_url: 'http://%server_name%/_test.php'
    mink.coverage_script_url: 'http://%server_name%/bundles/mink/phpunit_coverage.php'
    server: dev
    google_maps_key: 'AIzaSyAY1u4_NA6UsJa4gDfTZjmQ6-18dxxeC24'
    payment_report_path: /tmp
    authorize_net:
        login_id: '7hNc5K44'
        transaction_key: '5588K4QpHFhhqL5A'
        sandbox: true
    heartland:
        env: testing
        application_id: 3
        username: RTAPI
        password: $RTapi13
    login.attempts: 1
    login.delay: 1