parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
  database_name: cj_sf2
  database_user: root
  database_password: '123123'
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 50d18dbac33bbebe9fdd694d1d06d55499ce6d9d
  database_path: null
