imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: creditjeeves
    database_user: admin
    database_password: 'qwerty'

    server: local
    server_name: creditjeeves2.tonpc.forma-dev.com
