parameters:
    database_host: 127.0.0.1
    database_driver: pdo_mysql
    database_port: null
    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    mink.browser_name: 'firefox'
    mink.base_url: 'http://%server_name%/_test.php'
    server: dev

    experian.logging: true

    experian.pidkiq:
        url: 'https://dm2.experian.com/fraudsolutions/xmlgateway/preciseid' #required!
        userpwd: 'creditjeeves_pid_demo:ju3CVGlhX4' #required! # overwritten by DB
        eai: 'HRPCX4RA' #required! # overwritten by DB
        dbhost: 'PRECISE_ID_TEST' #required!
    experian.netConnect:
        url: 'http://www.experian.com/lookupServlet1?lookupServiceName=AccessPoint&lookupServiceVersion=1.0&serviceName=NetConnectDemo&serviceVersion=2.0&responseType=text/plain' #required!
        userpwd: 'creditjeeves_cs_demo:cAO2Ajd3f9' #required! # overwritten by DB
        eai: 'HRPCX4RA' #required! # overwritten by DB
        dbhost: 'STAR' #required!
    experian.atb:
        default_cash: 1000
        skip_sim_type_400: true
        wsdl_url: '%data.dir%/wsdl/ATBWebService.wsdl'
        location: 'http://stg.creditjeeves.com:8080/'
        logging: %experian.logging%
        logs_dir: '%kernel.logs_dir%'
    authorize_net:
        login_id: '54PB5egZ'
        transaction_key: '48V258vr55AE8tcg'
        sandbox: true
