imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: root
    database_password: '111111'

    experian.logging: false

    server: local
    server_name_cj: rj.loc
    server_name_rj: rj.loc

    secrets_path: /home/artem/

    mailer_transport: smtp
    mailer_host: 'localhost:1025' #for Mailcatcher
    mailer_user: null
    mailer_password: null
    mailer_delivery_address: 'staging@renttrack.com'  # force all email to be delivered to test mailbox
    mailer_disable_delivery: false