imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: credit_jeeves2
    database_password: 'passw0rd'

    experian.logging: false

    server: local
    server_name_cj: cj2.dev
    server_name_rj: rj1.dev
