imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: credit_jeeves
    database_password: 'passw0rd'

    server_name: dev2.creditjeeves.com

    mink_webdriver_host: 'http://10.46.179.1:4444/wd/hub'
