imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: credit_jeeves2
    database_password: 'passw0rd'

    experian.logging: false

    server: local
    server_name_cj: cj.loc
    server_name_rj: cj-rent.loc

    payment_processor.hps.report_path: /home/tatyana/tmp
    transunion.ssl_key: /home/tatyana/transunion.com/stg.renttrack.com.key
    transunion.ca_certificate: /home/tatyana/transunion.com/prodsupCA.pem
    transunion.ssl_certificate: /home/tatyana/transunion.com/CC2RentTrack-Test.crt
