parameters:
    database_host: localhost
    database_driver: pdo_mysql
    database_port: null

    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_delivery_address: 'staging@renttrack.com'  # force all email to be delivered to test mailbox
    mailer_disable_delivery: false

    session.lifetime:  3600 #in seconds
    mink.browser_name: 'firefox'
    mink.base_url: 'http://%server_name%/_test.php'
    mink.coverage_script_url: 'http://%server_name%/bundles/mink/phpunit_coverage.php'
    server: dev

    google_maps_key: 'AIzaSyBsW5-jPDZ2C-l9d62DVgdvQMerbt0XvNo' # API account with staging@renttrack.com

    aci.collect_pay.business_id: 563376

    payment_processor.hps.report_path: /tmp
    heartland:
        env: testing
        application_id: 3
        username: RTAPI
        password: $RTapi13
    aci_collect_pay:
        sandbox: true
        businessId: 563375
        login: RentTrackEnrollConnect
        password: KI9DPqXaJ8
    aci_pay_anyone:
        sandbox: true
        acquirerId: 564727
        login: RentTrackConnectUser
        password: KwJBDWruMsOL
        dateClient: 20141006
        name: RentTrack

    login.attempts: 1
    login.delay: 1
    net_connect.precise_id.userpwd: 'renttrack_pid_demo:d8ccULH0IcEn' #required! # overwritten by DB
    net_connect.precise_id.eai: 'HRPCX4RA' #required! # overwritten by DB
    net_connect.precise_id.url: 'https://dm2.experian.com/fraudsolutions/xmlgateway/preciseid' #required!
    net_connect.precise_id.dbhost: 'PRECISE_ID_TEST' #required!
    net_connect.precise_id.sub_code: '2279720' #required!
    net_connect.credit_profile.url: 'http://www.experian.com/lookupServlet1?lookupServiceName=AccessPoint&lookupServiceVersion=1.0&serviceName=NetConnectDemo&serviceVersion=2.0&responseType=text/plain' #required!
    net_connect.credit_profile.userpwd: 'renttrack_nc_demo:9yFUVWGusS7r' #required! # overwritten by DB
    net_connect.credit_profile.eai: 'HRPCX4RA' #required! # overwritten by DB
    net_connect.credit_profile.dbhost: 'STAR' #required!
    net_connect.credit_profile.sub_code: '2266580' #required!
    net_connect.credit_profile.d2c.sub_code: '2266580' #required!

    pidkiq.lifetime.minutes: 10

    soap.api.yardi.entity: RentTrack
    soap.api.yardi.license: V100057742BP.lic
    soap.api.yardi.path_to_classes: RentJeeves\ExternalApiBundle\Services\Yardi\Soap\

    validator.translation_domain: messages

    # parameter was added for task RT-362, we can fast allow and disallow feature that disallow duplicate contract
    allow_duplicate_contracts: false

    resman.integration_partner_id: 1073
    resman.api_key: e2344f3b0fd6482c8978e0dcab3d42db
    resman.api_url: https://api.myresman.com/MITS/

    pdo.db_options:
        db_table:        session
        db_id_col:       session_id
        db_data_col:     session_value
        db_time_col:     session_time

    transunion.account_name: 'CC2RentTrack'
    transunion.password: 'Pfr5Nm$c'
    transunion.environment: stage
    transunion.ssl_key: /var/www/%server_name_rj%/app/config/secrets/transunion/stg.renttrack.com.key
    transunion.ca_certificate: /var/www/%server_name_rj%/app/config/secrets/transunion/prodsupCA.pem
    transunion.ssl_certificate: /var/www/%server_name_rj%/app/config/secrets/transunion/CC2RentTrack-Test.crt
    transunion.renttrack_snapshot_bundle: 'CC2RentTrackTUReportSnapshot'
    transunion.renttrack_vantage_score_3_bundle: 'CC2RentTrackTUVantage3Score'

    monolog.email_from:         developers@renttrack.com
    monolog.alert.email_to:     staging@renttrack.com
    monolog.emergency.email_to: staging@renttrack.com
