parameters:
    database_host: 127.0.0.1
    database_driver: pdo_mysql
    database_port: null
    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    mink.browser_name: 'firefox'
    mink.base_url: 'http://%server_name%/_test.php'
    server: dev

    authorize_net:
        login_id: '7hNc5K44'
        transaction_key: '5588K4QpHFhhqL5A'
        sandbox: true
