parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: credit_jeeves
    database_user: root
    database_password: 'passw0rd2'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    api.admin_dealer_code: 1a1dc91c9073
    api.client_id: 1_qvxzb7ge734ko4ogwcskwksogoc0wskws40gg8oocokwg404s
    api.client_secret: 39uyn651qlk4ssws40sgs44cwsskgccoc0o04ccgsccgooowwo
    server: live
    server_name_cj: my.creditjeeves.com
    server_name_rj: renttrack.com
    google_maps_key: AIzaSyAY1u4_NA6UsJa4gDfTZjmQ6-18dxxeC24
    session.lifetime: 3600 #in seconds
    payment_report_path: /home/heartland
    authorize_net:
        login_id: '29fDg7sU24G'
        transaction_key: '474v43G35wJ6Gm2d'
        sandbox: false

    heartland:
        application_id: 1
        username: RTAPI
        password: $RTapi13
