parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: renttrack
    database_user: root
    database_password: 'passw0rd'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    api.admin_dealer_code: 1a1dc91c9073
    api.client_id: 1_qvxzb7ge734ko4ogwcskwksogoc0wskws40gg8oocokwg404s
    api.client_secret: 39uyn651qlk4ssws40sgs44cwsskgccoc0o04ccgsccgooowwo
    server: live
    server_name_cj: my.creditjeeves.com
    server_name_rj: my.renttrack.com
    google_maps_key: AIzaSyAY1u4_NA6UsJa4gDfTZjmQ6-18dxxeC24
    session.lifetime: 900 #in seconds
    payment_report_path: /home/heartland
    authorize_net:
        login_id: '29fDg7sU24G'
        transaction_key: '474v43G35wJ6Gm2d'
        sandbox: false

    heartland:
        application_id: 1
        username: RTAPI
        password: $RTapi13


    net_connect.precise_id.url: 'https://ss3.experian.com/fraudsolutions/xmlgateway/preciseid' #required!
    net_connect.precise_id.dbhost: 'PRECISE_ID' #required!
    net_connect.precise_id.sub_code: '2279720' #required!
    net_connect.credit_profile.url: 'http://www.experian.com/lookupServlet1?lookupServiceName=AccessPoint&lookupServiceVersion=1.0&serviceName=NetConnect&serviceVersion=2.0&responseType=text/plain' #required!
    net_connect.credit_profile.dbhost: 'CIS' #required!
    net_connect.credit_profile.sub_code: '2266580' #required!
    net_connect.credit_profile.d2c.sub_code: '2266580' #required!

    soap.api.yardi.entity: RentTrack
    soap.api.yardi.license: "./src/RentJeeves/ExternalApiBundle/Resources/files/V100057742BP.lic"

