parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
  database_name: credit_jeeves
  database_user: root
  database_password: '123123'
  mailer_transport: mail
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  server_name: cj2
