imports:
    - { resource: parameters_dev_base.yml }

parameters:
    database_name: credit_jeeves2
    database_user: root
    database_password: 123456

    experian.logging: false

    server: local
    server_name_cj: dev.renttrack.com
    server_name_rj: dev.renttrack.com
