jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        custom:
            id: user.user_provider

    firewalls:
        main:
            pattern: .*
            form_login:
                provider: custom 
                csrf_provider: form.csrf_provider
                success_handler: user.service.login_success_handler
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,     role: ROLE_ADMIN }
        - { path: ^/,           role: ROLE_USER }
# We'll additional pages
#       - { path: ^/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
#       - { path: ^/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
