security:
    encoders:
        CreditJeeves\DataBundle\Entity\User:
            id: user.security.encoder.digest

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        custom:
            id: user.user_provider

    firewalls:
        main:
            pattern: .*
            form_login:
                provider: custom 
                csrf_provider: form.csrf_provider
                success_handler: user.service.login_success_handler
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/_behat/tests/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new$,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/invite,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/message,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,        role: ROLE_USER }
        - { path: ^/,              role: ROLE_USER }

# We'll additional pages
#       - { path: ^/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
#       - { path: ^/resetting,  role: IS_AUTHENTICATED_ANONYMOUSLY }
