payment_accounts:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/PaymentAccountsController.php"
  name_prefix:  api_

payments:
  type:         rest
  resource:     "@RjApiBundle/Controller/Tenant/PaymentsController.php"
  name_prefix:  api_