parameters:
    wrapper.class: RentJeeves\ApiBundle\Serializer\WrapperHandler
    wrapper_collection.class: RentJeeves\ApiBundle\Serializer\CollectionWrapperHandler
    wrapper.type: NeedWrapped
    collection.class: RentJeeves\ApiBundle\ResponseEntity\ResponseCollection

services:
    wrapper.handler:
        class: "%wrapper.class%"
        tags:
            - { name: "jms_serializer.handler", type: "%wrapper.type%", format: json, method: wrapUnit }
    wrapper_collection.handler:
        class: "%wrapper_collection.class%"
        tags:
            - { name: "jms_serializer.handler", type: "%collection.class%", format: json, method: serializeCollection }
