parameters:
    import.mapping.csv.class: RentJeeves\LandlordBundle\Accounting\Import\Mapping\MappingCsv
    import.mapping.yardi.class: RentJeeves\LandlordBundle\Accounting\Import\Mapping\MappingYardi

services:
    accounting.import.mapping.csv:
        class: "%import.mapping.csv.class%"
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
        arguments:
            - "@accounting.import.storage.csv"
            - "@import.reader.csv"
    accounting.import.mapping.yardi:
        class: "%import.mapping.yardi.class%"
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
        arguments:
            - "@accounting.import.storage.yardi"
            - "@import.reader.csv"
            - "@yardi.resident_data"
