parameters:
    import.mapping.amsi.class: RentJeeves\LandlordBundle\Accounting\Import\Mapping\MappingAMSI
    import.mapping.csv.class: RentJeeves\LandlordBundle\Accounting\Import\Mapping\MappingCsv
    import.mapping.yardi.class: RentJeeves\LandlordBundle\Accounting\Import\Mapping\MappingYardi
    import.mapping.resman.class: RentJeeves\LandlordBundle\Accounting\Import\Mapping\MappingResman
    import.mapping.mri.class: RentJeeves\LandlordBundle\Accounting\Import\Mapping\MappingMRI
    accounting.export.yardi_genesis_v2.class: RentJeeves\LandlordBundle\Accounting\Export\Report\YardiGenesisV2Report
    accounting.export.yardi_genesis_v2_archive.class: RentJeeves\LandlordBundle\Accounting\Export\Report\YardiGenesisV2Archive
    export.serializer.yardi_genesis_v2.class: RentJeeves\LandlordBundle\Accounting\Export\Serializer\YardiGenesisV2CsvSerializer
    landlord.contract_manager.class: RentJeeves\LandlordBundle\Services\LandlordContractManager

services:
    accounting.import.storage.csv:
         class: RentJeeves\LandlordBundle\Accounting\Import\Storage\StorageCsv
         arguments:
             - "@session"
             - "@monolog.logger.import"
             - "@doctrine.orm.entity_manager"
             - "@core.session.landlord"
    accounting.import.storage.mri:
        class: RentJeeves\LandlordBundle\Accounting\Import\Storage\StorageMRI
        parent: accounting.import.storage.csv
    accounting.import.storage.amsi:
        class: RentJeeves\LandlordBundle\Accounting\Import\Storage\StorageAMSI
        parent: accounting.import.storage.csv
    accounting.import.storage.resman:
        class: RentJeeves\LandlordBundle\Accounting\Import\Storage\StorageResman
        parent: accounting.import.storage.csv
    accounting.import.storage.yardi:
        class: RentJeeves\LandlordBundle\Accounting\Import\Storage\StorageYardi
        parent: accounting.import.storage.csv
    landlord.contract_manager:
        class: "%landlord.contract_manager.class%"
        arguments:
            - "@translator"
            - "@resident_manager"
            - "@doctrine.orm.entity_manager"
            - "@checkout.paid_for"
    accounting.import.mapping.csv:
        class: "%import.mapping.csv.class%"
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setPropertyProcess, ["@property.manager"]]
        arguments:
            - "@accounting.import.storage.csv"
            - "@import.reader.csv"
    accounting.import.mapping.resman:
        class: "%import.mapping.resman.class%"
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setPropertyProcess, ["@property.manager"]]
        arguments:
            - "@accounting.import.storage.resman"
            - "@import.reader.csv"
            - "@resman.resident_data"
            - "@security.context"
    accounting.import.mapping.amsi:
        class: "%import.mapping.amsi.class%"
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setPropertyProcess, ["@property.manager"]]
        arguments:
            - "@accounting.import.storage.amsi"
            - "@import.reader.csv"
            - "@amsi.resident_data"
            - "@security.context"
    accounting.import.mapping.mri:
        class: "%import.mapping.mri.class%"
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setPropertyProcess, ["@property.manager"]]
        arguments:
            - "@accounting.import.storage.mri"
            - "@import.reader.csv"
            - "@mri.resident_data"
            - "@security.context"
    accounting.import.mapping.yardi:
        class: "%import.mapping.yardi.class%"
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setPropertyProcess, ["@property.manager"]]
        arguments:
            - "@accounting.import.storage.yardi"
            - "@import.reader.csv"
            - "@yardi.resident_data"
    accounting.export.yardi_genesis_v2:
        class: "%accounting.export.yardi_genesis_v2.class%"
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@export.serializer.yardi_genesis_v2"
            - "@soft.deleteable.control"
    accounting.export.yardi_genesis_v2_archive:
        class: "%accounting.export.yardi_genesis_v2_archive.class%"
        arguments:
            - "@accounting.export.yardi_genesis_v2"
            - "@export.serializer.yardi_genesis_v2"
    export.serializer.yardi_genesis_v2:
        class: "%export.serializer.yardi_genesis_v2.class%"
        arguments:
            - "@jms_serializer"

    # Landlord import
    accounting.landlord_import.importer:
        class: RentJeeves\LandlordBundle\Accounting\ImportLandlord\LandlordCsvImporter
        arguments:
            - @reader.csv
            - @doctrine.orm.entity_manager
            - @accounting.landlord_import.group_mapper
            - @accounting.landlord_import.landlord_mapper
            - @accounting.landlord_import.unit_mapper
            - @validator
        calls:
            - [setLogger, ["@logger"]]

    accounting.landlord_import.abstract_mapper:
        abstract: true
        public: false
        calls:
            - [setLogger, ["@logger"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    accounting.landlord_import.group_mapper:
        class: RentJeeves\LandlordBundle\Accounting\ImportLandlord\Mapping\GroupMapper
        parent: accounting.landlord_import.abstract_mapper
        arguments:
            - @address_lookup_service
            - { fee_cc: %paydirect_fee_cc%, fee_ach: %paydirect_fee_ach%, division_id: %aci.collect_pay.business_id% }

    accounting.landlord_import.landlord_mapper:
        class: RentJeeves\LandlordBundle\Accounting\ImportLandlord\Mapping\LandlordMapper
        parent: accounting.landlord_import.abstract_mapper
        arguments:
            - %kernel.default_locale%

    accounting.landlord_import.unit_mapper:
        class: RentJeeves\LandlordBundle\Accounting\ImportLandlord\Mapping\UnitMapper
        parent: accounting.landlord_import.abstract_mapper
        arguments:
            - @property.manager

    landlord.batch_deposits.manager:
        class: RentJeeves\LandlordBundle\Services\BatchDepositsManager
        arguments:
            - @doctrine.orm.entity_manager
