parameters:
    support_email: help@rentjeeves.com
    support_phone: (866)-976-6622

    email_from: support@renttjeeves.com
    email_name: Credit Jeeves
    email_admins:
        - alex.emelyanov.ua@gmail.com
        - darryl@rentjeeves.com

    date_short: 'M j, Y'
    date_full: 'F j, Y'

    external_urls:
        main_site: 'www.rentjeeves.com'
        user_voice: 'creditjeeves.uservoice.com'
