security:
    encoders:
        CreditJeeves\DataBundle\Entity\User:
            id: user.security.encoder.digest

    role_hierarchy:
        ROLE_ADMIN:    ROLE_ADMIN
        ROLE_TENANR:   ROLE_TENANT
        ROLE_LANDLORD: ROLE_LANDLORD

    providers:
        custom:
            id: user.user_provider
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false
        oauth_authorize:
            pattern: ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: ~
        main:
            pattern: ^/
            form_login:
                provider: custom 
                csrf_provider: form.csrf_provider
                success_handler: user.service.login_success_handler
                failure_handler: user.service.login_failure_handler
                failure_path:  null
                failure_forward: false
            logout:       true
            anonymous:    true
            remember_me:
                key: HKSHDY2PWUSGBNP88YTAT262Y2
                secure: true
                httponly: true

    access_control:
        - { path: ^/oauth/v2/auth_login,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth_reg,              role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/token,                 role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth,                  role: ROLE_TENANT }
        - { path: ^/back_to_admin$,                 role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt/,                          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/*,                           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/*,                          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/landlord/ajax/property/add$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/i18n/*,                         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tenant/invite/*,                role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/landlord/invite/*,              role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/validator/*,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/management,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/,                     role: ROLE_LANDLORD }
        - { path: ^/_profiler/,                     role: ROLE_TENANT }
        - { path: ^/test,                           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,                         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,                      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/invite,                         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/message,                        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/iframe,                         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public_iframe,                  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/landlord/register,              role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checkProperty/*,                role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/invite,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/new,                       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/check/*,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/translations,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/defence/*,                role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/defence/*,                role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new/send/*,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/landlord/,                      role: ROLE_LANDLORD }
        - { path: ^/api/tenant,                     role: ROLE_TENANT }
        - { path: ^/api/partner,                    role: ROLE_PARTNER }
        - { path: ^/admin/,                         role: ROLE_ADMIN, ips: [166.176.58.190, 50.157.126.16, 70.191.93.110, 70.197.20.82, 71.211.222.170, 75.168.20.203, 166.170.14.30, 107.184.229.255, 198.72.148.19, 185.67.87.66, 97.92.80.220, ::1] }
        - { path: ^/admin/,                         role: ROLE_NO_ACCESS }
        - { path: ^/documentation/api,              role: ROLE_ADMIN }
        - { path: ^/,                               role: ROLE_TENANT }
