twig:
    form:
        resources:
            - 'LandlordBundle:Form:view.html.twig'
            - 'CoreBundle:Form:view_hidden.html.twig'
    globals:
        serverName: '%server_name_rj%'
        external_urls: %external_urls%
