parameters:
    experian.net_connect.credit_profile.class: CreditJeeves\TestBundle\NetConnect\CreditProfileTest
    experian.net_connect.precise_id.class: CreditJeeves\TestBundle\NetConnect\PreciseIDTest
    mink.driver.selenium2.class: CreditJeeves\TestBundle\Tests\Driver\Selenium2Driver
    credit_services:
        credit_summary_vendor: experian # supported values are 'transunion' or 'experian'
