services:
    sonata.admin.jobs:
        class: RentJeeves\AdminBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Jobs" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Job
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.payments:
        class: RentJeeves\AdminBundle\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Payments" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Payment
            - 'RjAdminBundle:PaymentAdmin'

    sonata.admin.payment.accounts:
        class: RentJeeves\AdminBundle\Admin\PaymentAccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Paymnet accounts" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\PaymentAccount
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.rj_email:
        class: RentJeeves\AdminBundle\Admin\EmailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Holdings" }
        arguments:
            - ~
            - Rj\EmailBundle\Entity\EmailTemplate
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:form_email_template_edit.html.twig]]
            - [ setLocales, [%rj_email.locales%]]

    sonata.admin.rj_holding:
        class: RentJeeves\AdminBundle\Admin\RjHoldingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Holdings" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Holding
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:holding_edit.html.twig]]
            - [ setTranslationDomain, [messages]]

    sonata.admin.rj_group:
        class: RentJeeves\AdminBundle\Admin\RjGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Groups" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:group_edit.html.twig]]
            - [ setTranslationDomain, [messages]]

    sonata.admin.rj_group_phone:
        class: RentJeeves\AdminBundle\Admin\GroupPhoneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "GroupsPhones" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\GroupPhone
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.deposit_account:
        class: RentJeeves\AdminBundle\Admin\DepositAccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "DepositAccount" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\DepositAccount
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [messages]]


    sonata.admin.landlord:
        class: RentJeeves\AdminBundle\Admin\LandlordAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Landlords" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Landlord
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:form_edit_user_custom_actions.html.twig]]
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.tenant:
        class: RentJeeves\AdminBundle\Admin\TenantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Tenants" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Tenant
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:form_edit_user_custom_actions.html.twig]]
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.contract:
        class: RentJeeves\AdminBundle\Admin\ContractAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Contracts" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Contract
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:form_contract.html.twig]]
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.property:
        class: RentJeeves\AdminBundle\Admin\PropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Properties" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Property
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.unit:
        class: RentJeeves\AdminBundle\Admin\UnitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Units" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Unit
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.heartland:
        class: RentJeeves\AdminBundle\Admin\HeartlandAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Heartland logs" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Transaction
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.operations:
        class: RentJeeves\AdminBundle\Admin\OperationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Operations" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Operation
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.contract_waiting:
        class: RentJeeves\AdminBundle\Admin\ContractWaitingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Contract Waiting" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\ContractWaiting
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:form_contract_waiting.html.twig]]
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.resident_mapping:
        class: RentJeeves\AdminBundle\Admin\ResidentMappingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Resident Mapping" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\ResidentMapping
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:form_resident_mapping.html.twig]]
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.property_mapping:
        class: RentJeeves\AdminBundle\Admin\PropertyMappingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Property Mapping" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\PropertyMapping
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.unit_mapping:
        class: RentJeeves\AdminBundle\Admin\UnitMappingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Unit Mapping" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\UnitMapping
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTemplate, [edit, AdminBundle:CRUD:form_edit_unit_mapping.html.twig]]
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.partners:
        class: RentJeeves\AdminBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Partners" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Partner
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.user_partner:
        class: RentJeeves\AdminBundle\Admin\PartnerUsersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Partner users" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\PartnerUser
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.settings:
        class: RentJeeves\AdminBundle\Admin\SettingsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Settings" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Settings
            - 'SonataAdminBundle:CRUD'

    sonata.admin.outbound_transaction:
        class: RentJeeves\AdminBundle\Admin\OutboundTransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Outbound Transactions" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\OutboundTransaction
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [messages]]

    sonata.admin.import_report:
        class: RentJeeves\AdminBundle\Admin\ImportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Import Reports" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Import
            - ~

    sonata.admin.import_property:
        class: RentJeeves\AdminBundle\Admin\ImportPropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Import Property" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\ImportProperty
            - ~

    rental_report:
        class: RentJeeves\AdminBundle\Form\RentalReportType
        tags:
            - { name: form.type, alias: rental_report }

    form.import_group_settings:
        class: RentJeeves\AdminBundle\Form\ImportGroupSettingsType
        tags:
            - { name: form.type, alias: import_group_settings }

    profit_stars_settings_type:
        class: RentJeeves\AdminBundle\Form\ProfitStarsSettingsType
        tags:
            - { name: form.type, alias: profit_stars_settings_type }

    csv.mapping.creator:
        class: RentJeeves\AdminBundle\Services\CsvMappingCreator
        arguments:
            - @doctrine.orm.default_entity_manager
            - @import.reader.csv
            - @translator
            - @form.factory

    form.upload_csv_file:
        class: RentJeeves\AdminBundle\Form\UploadCsvFileType