services:
    sonata.admin.rj_holding:
        class: RentJeeves\AdminBundle\Admin\RjHoldingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Holdings" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Holding
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.rj_group:
        class: RentJeeves\AdminBundle\Admin\RjGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Groups" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.landlord:
        class: RentJeeves\AdminBundle\Admin\LandlordAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Landlords" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Landlord
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.tenant:
        class: RentJeeves\AdminBundle\Admin\TenantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Tenants" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Tenant
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.contract:
        class: RentJeeves\AdminBundle\Admin\ContractAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Contracts" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Contract
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.orders:
        class: RentJeeves\AdminBundle\Admin\OrderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Payments" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Order
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.property:
        class: RentJeeves\AdminBundle\Admin\PropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Properties" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Property
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.unit:
        class: RentJeeves\AdminBundle\Admin\UnitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Units" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Unit
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]