services:
    sonata.admin.jobs:
        class: RentJeeves\AdminBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Jobs" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Job
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.payments:
        class: RentJeeves\AdminBundle\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Payments" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Payment
            - 'RjAdminBundle:PaymentAdmin'

    sonata.admin.payment.accounts:
        class: RentJeeves\AdminBundle\Admin\PaymentAccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Paymnet accounts" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\PaymentAccount
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.rj_email:
        class: RentJeeves\AdminBundle\Admin\EmailTemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Holdings" }
        arguments:
            - ~
            - Rj\EmailBundle\Entity\EmailTemplate
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setLocales, [%rj_email.locales%]]

    sonata.admin.rj_holding:
        class: RentJeeves\AdminBundle\Admin\RjHoldingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Holdings" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Holding
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.rj_group:
        class: RentJeeves\AdminBundle\Admin\RjGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Groups" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Group
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.rj_group.phone:
        class: RentJeeves\AdminBundle\Admin\GroupPhoneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Groups" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\GroupPhone
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]



    sonata.admin.landlord:
        class: RentJeeves\AdminBundle\Admin\LandlordAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Landlords" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Landlord
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.tenant:
        class: RentJeeves\AdminBundle\Admin\TenantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Tenants" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Tenant
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.contract:
        class: RentJeeves\AdminBundle\Admin\ContractAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Contracts" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Contract
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.property:
        class: RentJeeves\AdminBundle\Admin\PropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Properties" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Property
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.unit:
        class: RentJeeves\AdminBundle\Admin\UnitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Units" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Unit
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.heartland:
        class: RentJeeves\AdminBundle\Admin\HeartlandAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: RentJeeves, label: "Heartland logs" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\Heartland
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]

    sonata.admin.operations:
        class: RentJeeves\AdminBundle\Admin\OperationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Operations" }
        arguments:
            - ~
            - CreditJeeves\DataBundle\Entity\Operation
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]
    sonata.admin.resident_mapping:
        class: RentJeeves\AdminBundle\Admin\ResidentMappingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Resident Mapping" }
        arguments:
            - ~
            - RentJeeves\DataBundle\Entity\ResidentMapping
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CreditJeevesAdminBundle]]
