parameters:
    doctrine.dbal.connection.wrapper_class: ~
    translator.class: 'CreditJeeves\CoreBundle\Translation\Translator'
    date_short: 'M j, Y'
    date_full: 'F j, Y'
    email_admins:
        - alex.emelyanov.ua@gmail.com
        - darryl@creditjeeves.com
    experian.logging: false
    login.attempts: 5
    login.delay: 30

simulation:
    entity_name: '\CreditJeeves\DataBundle\Entity\Atb'
    atb: ~

services:
  gedmo.listener.softdeleteable:
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

api:
  username: '9ZKHHdEa47nzF9O0Of+vv1cKXGQUAOd/xJ6UcsY1Hxw='
  password: '1SgQfQvenIhG3URtUOBrkN8DEO4ZAeb284cMEVL5E7k='
  admin_dealer_code: 1a1dc91c9073
  pidkiq_precisel_id_type: 11
  pidkiq_subcode: 1908357

