parameters:
    date_short: 'M j, Y'
    date_full: 'F j, Y'
    email_admins:
        - alex.emelyanov.ua@gmail.com
        - darryl@creditjeeves.com

    experian.logging: false
    experian.atb:
        wsdl_url: '%data.dir%/wsdl/ATBWebService.wsdl'
        location: 'http://stg.creditjeeves.com:8080/'
        logging: %experian.logging%
        logs_dir: '%kernel.logs_dir%'