parameters:
    date_short: 'M j, Y'
    date_full: 'F j, Y'
    email_admins:
        - alex.emelyanov.ua@gmail.com
        - darryl@creditjeeves.com
    experian.logging: false

simulation:
    entity_name: '\CreditJeeves\DataBundle\Entity\Atb'
    atb: ~