parameters:
    doctrine.dbal.connection.wrapper_class: ~
    translator.class: 'CreditJeeves\CoreBundle\Translation\Translator'
    date_short: 'M j, Y'
    date_full: 'F j, Y'
    email_admins:
        - darryl@creditjeeves.com
    experian.logging: false
    login.attempts: 6
    login.delay: 30

    credit_services:
        credit_summary_vendor: transunion # supported values are 'transunion' or 'experian'

simulation:
    entity_name: '\CreditJeeves\DataBundle\Entity\Atb'
    atb: ~

services:
  gedmo.listener.softdeleteable:
    class: Gedmo\SoftDeleteable\SoftDeleteableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

api:
  username: '9ZKHHdEa47nzF9O0Of+vv1cKXGQUAOd/xJ6UcsY1Hxw='
  password: '1SgQfQvenIhG3URtUOBrkN8DEO4ZAeb284cMEVL5E7k='
  admin_dealer_code: 1a1dc91c9073
  pidkiq_precisel_id_type: 6
  pidkiq_subcode: 2108720
  pidkiq_end_user: 'US Equity Advantage'
  pidkiq_account_type: 0B
  pidkiq_xml_version: 5
