parameters:
    translator.class: 'CreditJeeves\CoreBundle\Translation\Translator'
    date_short: 'M j, Y'
    date_full: 'F j, Y'
    email_admins:
        - alex.emelyanov.ua@gmail.com
        - darryl@creditjeeves.com
    experian.logging: false
    login.attempts: 5
    login.delay: 30

simulation:
    entity_name: '\CreditJeeves\DataBundle\Entity\Atb'
    atb: ~
