doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        wrapper_class: %doctrine.dbal.connection.wrapper_class%
    orm:
        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
                str_to_date: DoctrineExtensions\Query\Mysql\StrToDate
                day: DoctrineExtensions\Query\Mysql\Day
                last_day: DoctrineExtensions\Query\Mysql\LastDay
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
                dateadd: DoctrineExtensions\Query\Mysql\DateAdd
            string_functions:
                field: DoctrineExtensions\Query\Mysql\Field
                concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                if: DoctrineExtensions\Query\Mysql\IfElse
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        auto_generate_proxy_classes: %kernel.debug%
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            # @see  http://stackoverflow.com/questions/24873780/error-with-doctrineschemavalidate-for-payum-token
            payum:
                is_bundle: false
                type: xml
                dir: %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping

                prefix: Payum\Core\Model
        auto_mapping: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true
#            gedmo_loggable: true
            loggable: true
    class:
        loggable: CreditJeeves\DataBundle\EventListener\LoggableListener
    uploadable:
        validate_writable_directory: false

