parameters:
    experian.logging: false
    experian.pidkiq:
        url: 'https://dm2.experian.com/fraudsolutions/xmlgateway/preciseid' #required!
        userpwd: 'creditjeeves_pid_demo:Tjl80jvE5N' #required! # overwritten by DB
        eai: 'HRPCX4RA' #required! # overwritten by DB
        dbhost: 'PRECISE_ID_TEST' #required!
    experian.netConnect:
        url: 'http://www.experian.com/lookupServlet1?lookupServiceName=AccessPoint&lookupServiceVersion=1.0&serviceName=NetConnectDemo&serviceVersion=2.0&responseType=text/plain' #required!
        userpwd: 'creditjeeves_cs_demo:e1oKIoRUPW' #required! # overwritten by DB
        eai: 'HRPCX4RA' #required! # overwritten by DB
        dbhost: 'STAR' #required!
    experian.atb:
        wsdl_url: '%data.dir%/wsdl/ATBWebService.wsdl'
        location: 'http://stg.creditjeeves.com:8080/'
        logging: %experian.logging%
        logs_dir: '%kernel.logs_dir%'
    authorize_net:
        login_id: '7hNc5K44'
        transaction_key: '5588K4QpHFhhqL5A'
        sandbox: true
