framework:
    translator:      { fallback: en }
    secret:          50d18dbac33bbebe9fdd694d1d06d55499ce6d9v
    router:
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "en"
    trusted_proxies: ~
    session: ~
