jms_di_extra:
    locations:
        all_bundles: true
    automatic_controller_injections:
        method_calls:
            setContainer: ["@service_container"]

jms_security_extra:
    secure_all_services: false
    expressions: true
