jms_di_extra:
    locations:
        all_bundles: true
    automatic_controller_injections:
        method_calls:
            setContainer: ["@service_container"]

jms_security_extra:
    secure_all_services: false
    expressions: true

jms_job_queue:
    statistics: false

jms_serializer:
    handlers:
        datetime:
            default_format: "F d, Y"
            default_timezone: "PST"
