monolog:
    channels: ["import", "rjDueEmail", "property_import", "contract_movement_manager", "unit_deduplicator", "property_deduplicator", "contract_sync", "profit_stars", 'sftp_file_manager']
    handlers:
        main:
            type:         fingers_crossed
            action_level: debug
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        property_import:
            level:      debug
            type:       stream
            path:       '%kernel.logs_dir%/property_import_%kernel.environment%.log'
            channels:   [property_import]
            formatter:  monolog.formatter.import
        swift_emergency:
            type:       swift_mailer
            from_email: %monolog.email_from%
            to_email:   %monolog.emergency.email_to%
            subject:    SYSTEM EMERGENCY
            level:      emergency
            bubble:     false # @link https://github.com/Seldaek/monolog#core-concepts
        swift_alert:
            type:       swift_mailer
            from_email: %monolog.email_from%
            to_email:   %monolog.alert.email_to%
            subject:    SYSTEM ALERT
            level:      alert

services:
    # property import logger
    monolog.formatter.import:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.Group#%%extra.group_id%%.%%level_name%%: %%message%% [type = %%extra.import_type%%; additional_parameter = %%extra.additional_parameter%%]\n"

    monolog.processor.import:
        class: RentJeeves\ImportBundle\Logger\LoggerProcessor
        tags:
            - { name: monolog.processor, method: processRecord, handler: property_import }
