sonata_admin:
    title:      Credit Jeeves Admin
    title_logo: /bundles/core/images/logo/logo-small.png
    templates:
        # default global templates
        layout:  AdminBundle:Sonata:index.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
          admin: ~
          CreditJeeves:
            items:
              - sonata.admin.cj_group
              - sonata.admin.dealer
              - sonata.admin.applicant
          RentJeeves: ~

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]