parameters:
    experian.net_connect.credit_profile.class: RentJeeves\TestBundle\NetConnect\CreditProfileTest
    experian.net_connect.precise_id.class: RentJeeves\TestBundle\NetConnect\PreciseIDTest
    pidkiq.experian.pidkiq_api.class: RentJeeves\TestBundle\PidKiqProcessor\Experian\ExperianPidKiqApiClientTest
    payment_account.heartland.class: RentJeeves\TestBundle\Heartland\PaymentAccountManagerTest
    payment_processor.aci.collect_pay.report_loader.class: RentJeeves\TestBundle\Aci\CollectPayReportLoaderTest
    soap.client.yardi.resident_transactions.class: RentJeeves\TestBundle\Services\Yardi\Clients\ResidentTransactionsClient
    soap.client.amsi.leasing.class: 'RentJeeves\TestBundle\Services\AMSI\AMSILeasingClient'