applicant_homepage:
    pattern: /
    defaults: { _controller: ApplicantBundle:Homepage:index }

applicant_summary:
    pattern: /summary
    defaults: { _controller: ApplicantBundle:Summary:index }

applicant_password:
    pattern: /password
    defaults: { _controller: ApplicantBundle:Settings:password }

