applicant_homepage:
    pattern: /
    defaults: { _controller: ApplicantBundle:Homepage:index }

applicant_summary:
    pattern: /summary
    defaults: { _controller: ApplicantBundle:Summary:index }

applicant_password:
    pattern: /password
    defaults: { _controller: ApplicantBundle:Settings:password }

applicant_contact:
    pattern: /contact
    defaults: { _controller: ApplicantBundle:Settings:contact }

applicant_email:
    pattern: /email
    defaults: { _controller: ApplicantBundle:Settings:email }

applicant_remove:
    pattern: /remove
    defaults: { _controller: ApplicantBundle:Settings:remove }

applicant_new:
    pattern: /new
    defaults: { _controller: ApplicantBundle:New:index }

#applicant__invite:
#    pattern: /invite/{code}
#    defaults: { _controller: ApplicantBundle:Invite:index }
#    requirements:
#      code: '.+'
