applicant_homepage:
    pattern: /
    defaults: { _controller: ApplicantBundle:Homepage:index }

applicant_summary:
    pattern: /summary
    defaults: { _controller: ApplicantBundle:Summary:index }

applicant_new:
    pattern: /new
    defaults: { _controller: ApplicantBundle:New:index }

#applicant__invite:
#    pattern: /invite/{code}
#    defaults: { _controller: ApplicantBundle:Invite:index }
#    requirements:
#      code: '.+'
