parameters:
#    applicant.example.class: CreditJeeves\ApplicantBundle\Example

services:
#    applicant.example:
#        class: %applicant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
