parameters:
    core.event_listener.controller.class: CreditJeeves\ApplicantBundle\EventListener\Controller

services:
#    applicant.example:
#        class: %applicant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
