applicant_homepage:
    pattern:  /
    defaults: { _controller: ApplicantBundle:Homepage:index }

dealer_homepage:
    pattern:  /dealer
    defaults: { _controller: DealerBundle:Homepage:index }

admin_homepage:
  pattern: /admin
  defaults: { _controller: AdminBundle:Homepage:index }

