parameters:
    user.service.login_success_handler.class: CreditJeeves\UserBundle\Service\LoginSuccessHandler
    user.user_provider.class:                 CreditJeeves\UserBundle\Security\Provider\UserProvider
    user.security.encode.digest.class:        CreditJeeves\UserBundle\Security\Encoder\MessageDigestPasswordEncoder

services:
  user.service.login_success_handler:
    class: %user.service.login_success_handler.class%
    arguments: [@service_container, @security.context]
  user.user_provider:
        class: %user.user_provider.class%
        public: false
        arguments: [@fos_user.user_manager]
  user.security.encoder.digest:
        class: %user.security.encode.digest.class%
