parameters:
    besimple.soap.client.builder.class: 'RentJeeves\ExternalApiBundle\Soap\SoapClientBuilder'
    soap.client.factory.class: 'RentJeeves\ExternalApiBundle\Soap\SoapClientFactory'
    soap.client.yardi.payment.class:  'RentJeeves\ExternalApiBundle\Services\Yardi\Clients\PaymentClient'
    soap.client.yardi.resident_transactions.class: 'RentJeeves\ExternalApiBundle\Services\Yardi\Clients\ResidentTransactionsClient'
    soap.client.yardi.resident_data.class: 'RentJeeves\ExternalApiBundle\Services\Yardi\Clients\ResidentDataClient'
    resman.client.class: RentJeeves\ExternalApiBundle\Services\ResMan\ResManClient
    mri.client.class: RentJeeves\ExternalApiBundle\Services\MRI\MRIClient

services:
    mri.client:
        class: "%mri.client.class%"
        arguments:
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@logger"
    resman.client:
        class: "%resman.client.class%"
        arguments:
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@logger"
            - "%resman.integration_partner_id%"
            - "%resman.api_key%"
            - "%resman.api_url%"
    soap.client.factory:
        class: "%soap.client.factory.class%"
        arguments:
          - "@service_container"
    soap.client.yardi.payment:
        class: "%soap.client.yardi.payment.class%"
        arguments:
            - "@logger"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.yardi_payment"
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@kernel"
            - "%soap.api.yardi.entity%"
            - "%soap.api.yardi.license%"
            - "%soap.api.yardi.path_to_classes%"
    soap.client.yardi.resident_transactions:
        class: "%soap.client.yardi.resident_transactions.class%"
        arguments:
            - "@logger"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.yardi_resident_transactions"
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@kernel"
            - "%soap.api.yardi.entity%"
            - "%soap.api.yardi.license%"
            - "%soap.api.yardi.path_to_classes%"
    soap.client.yardi.resident_data:
        class: "%soap.client.yardi.resident_data.class%"
        arguments:
            - "@logger"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.yardi_resident_data"
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@kernel"
            - "%soap.api.yardi.entity%"
            - "%soap.api.yardi.license%"
            - "%soap.api.yardi.path_to_classes%"

