parameters:
    besimple.soap.client.builder.class: 'RentJeeves\ExternalApiBundle\Soap\SoapClientBuilder'
    soap.client.factory.class: 'RentJeeves\ExternalApiBundle\Soap\SoapClientFactory'
    soap.client.yardi.payment.class:  'RentJeeves\ExternalApiBundle\Services\Yardi\Clients\PaymentClient'
    soap.client.yardi.resident_transactions.class: 'RentJeeves\ExternalApiBundle\Services\Yardi\Clients\ResidentTransactionsClient'
    soap.client.yardi.resident_data.class: 'RentJeeves\ExternalApiBundle\Services\Yardi\Clients\ResidentDataClient'
    resman.client.class: 'RentJeeves\ExternalApiBundle\Services\ResMan\ResManClient'
    mri.client.class: 'RentJeeves\ExternalApiBundle\Services\MRI\MRIClient'
    soap.client.amsi.leasing.class: 'RentJeeves\ExternalApiBundle\Services\AMSI\Clients\AMSILeasingClient'
    soap.client.amsi.ledger.class: 'RentJeeves\ExternalApiBundle\Services\AMSI\Clients\AMSILedgerClient'
    binlist.source.class: 'RentJeeves\ExternalApiBundle\Services\Binlist\BinlistSource'
    binlist.card.class: 'RentJeeves\ExternalApiBundle\Services\Binlist\BinlistCard'

services:
    yardi.reversal_receipts:
        class: RentJeeves\ExternalApiBundle\Services\Yardi\ReversalReceiptSender
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@soap.client.factory"
            - "@jms_serializer"
            - "@logger"
    jira.rest_client:
        class: RentJeeves\ExternalApiBundle\Services\Jira\JiraClient
        arguments:
            - "@logger"
            - "%jira_api.hostname%"
            - "%jira_api.user%"
            - "%jira_api.password%"
            - "%jira_api.key%"
    trusted.landlord.jira.service:
        class: RentJeeves\ExternalApiBundle\Services\Jira\TrustedLandlordJiraService
        arguments:
            - "@jira.rest_client"
            - "@doctrine.orm.default_entity_manager"
            - "logger"

    yardi.resident_data:
        class: RentJeeves\ExternalApiBundle\Services\Yardi\ResidentDataManager
        arguments:
            - "@soap.client.factory"
            - "@logger"

    resman.resident_data:
        class: RentJeeves\ExternalApiBundle\Services\ResMan\ResidentDataManager
        arguments:
            - "@resman.client"
            - "@logger"

    contract_sync.factory:
        class: RentJeeves\ExternalApiBundle\Services\ContractSynchronizerFactory
        arguments:
            -
              %accounting_system.yardi%: "@yardi.contract_sync"
              %accounting_system.mri%: "@mri.contract_sync"
              %accounting_system.resman%: "@resman.contract_sync"
              %accounting_system.amsi%: "@amsi.contract_sync"

    base.contract_sync:
        abstract:  true
        class: RentJeeves\ExternalApiBundle\Services\AbstractContractSynchronizer
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@monolog.logger.contract_sync"

    yardi.contract_sync:
        parent: base.contract_sync
        class: RentJeeves\ExternalApiBundle\Services\Yardi\ContractSynchronizer
        calls:
            - [setResidentDataManager, ["@yardi.resident_data"]]

    resman.contract_sync:
        parent: base.contract_sync
        class: RentJeeves\ExternalApiBundle\Services\ResMan\ContractSynchronizer
        calls:
            - [setResidentDataManager, ["@resman.resident_data"]]

    mri.contract_sync:
        parent: base.contract_sync
        class: RentJeeves\ExternalApiBundle\Services\MRI\ContractSynchronizer
        calls:
            - [setResidentDataManager, ["@mri.resident_data"]]

    amsi.contract_sync:
        parent: base.contract_sync
        class: RentJeeves\ExternalApiBundle\Services\AMSI\ContractSynchronizer
        calls:
            - [setResidentDataManager, ["@amsi.resident_data"]]

    mri.client:
        class: "%mri.client.class%"
        arguments:
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@http_client"
            - "@logger"

    resman.client:
        class: "%resman.client.class%"
        arguments:
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@logger"
            - "%resman.integration_partner_id%"
            - "%resman.api_key%"
            - "@guzzle_client"

    soap.client.factory:
        class: "%soap.client.factory.class%"
        arguments:
          - "@service_container"
    soap.client.yardi.payment:
        class: "%soap.client.yardi.payment.class%"
        arguments:
            - "@logger"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.yardi_payment"
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@kernel"
            - "%soap.api.yardi.entity%"
            - "%soap.api.yardi.license%"
            - "%soap.api.yardi.path_to_classes%"
    soap.client.yardi.resident_transactions:
        class: "%soap.client.yardi.resident_transactions.class%"
        arguments:
            - "@logger"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.yardi_resident_transactions"
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@kernel"
            - "%soap.api.yardi.entity%"
            - "%soap.api.yardi.license%"
            - "%soap.api.yardi.path_to_classes%"
    soap.client.yardi.resident_data:
        class: "%soap.client.yardi.resident_data.class%"
        arguments:
            - "@logger"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.yardi_resident_data"
            - "@fp_badaboom.exception_catcher"
            - "@jms_serializer"
            - "@kernel"
            - "%soap.api.yardi.entity%"
            - "%soap.api.yardi.license%"
            - "%soap.api.yardi.path_to_classes%"
    soap.client.amsi.leasing:
        class: "%soap.client.amsi.leasing.class%"
        arguments:
            - "@logger"
            - "@fp_badaboom.exception_catcher"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.amsi_leasing"
            - "@jms_serializer"
    soap.client.amsi.ledger:
        class: "%soap.client.amsi.ledger.class%"
        arguments:
            - "@logger"
            - "@fp_badaboom.exception_catcher"
            - "@soap.wsdl.twig.renderer"
            - "@besimple.soap.client.amsi_ledger"
            - "@jms_serializer"

    binlist.debit_card_repo:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - RentJeeves\DataBundle\Entity\DebitCardBinlist
    binlist.source:
        class: "%binlist.source.class%"
        arguments:
            - "@logger"
            - "@reader.csv"
            - "@jms_serializer"
    binlist.card:
        class: "%binlist.card.class%"
        arguments:
            - "@binlist.debit_card_repo"

    renttrack.export.report:
        class: RentJeeves\ExternalApiBundle\Services\EmailNotifier\RentTrackExportReport
        parent: "accounting.export.renttrack"

    failed.post.payment.notifier:
        class: RentJeeves\ExternalApiBundle\Services\EmailNotifier\FailedPostPaymentNotifier
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@logger"
            - "@renttrack.export.report"
            - "@project.mailer"
