parameters:
    # using a path that leads into the project does not make sense. Use a path out of project if you need to.
    # Otherwise put transformers into ImportBundle.
    import.property.transformer.custom_paths: []
    import.lease.transformer.custom_paths: []

services:
    import_transformer.repository:
        class: RentJeeves\DataBundle\Entity\ImportTransformerRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - RentJeeves\DataBundle\Entity\ImportTransformer

    # builders
    import.property.extractor_builder:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\ExtractorBuilder
        arguments:
            - @import.property.extractor_factory
            - @monolog.logger.property_import

    import.lease.extractor_builder:
        class: RentJeeves\ImportBundle\LeaseImport\Extractor\ExtractorBuilder
        arguments:
            - '@import.lease.extractor_factory'
            - '@monolog.logger.lease_import'

    # factories
    import.property.extractor_factory:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\ExtractorFactory
        arguments:
            -
              %accounting_system.mri%: @import.property.extractor.mri
              %accounting_system.resman%: @import.property.extractor.resman
              %accounting_system.yardi%: @import.property.extractor.yardi
              %accounting_system.amsi%: @import.property.extractor.amsi
              %accounting_system.rent_manager%: @import.property.extractor.rent_manager
            - @import.property.extractor.csv

    import.property.transformer_factory:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\TransformerFactory
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import
            - %import.property.transformer.custom_paths%
            -
              %accounting_system.mri%: @import.property.transformer.mri
              %accounting_system.yardi%: @import.property.transformer.yardi
              %accounting_system.resman%: @import.property.transformer.resman
              %accounting_system.amsi%: @import.property.transformer.amsi
              %accounting_system.rent_manager%: @import.property.transformer.rent_manager
            - @import.property.transformer.csv

    import.lease.extractor_factory:
        class: RentJeeves\ImportBundle\LeaseImport\Extractor\ExtractorFactory
        public: false
        calls:
            - [setCsvExtractor, ['@import.lease.extractor.csv']]
            - [addApiExtractor, ['%accounting_system.resman%', '@import.lease.extractor.resman']]

    import.lease.transformer_factory:
        class: RentJeeves\ImportBundle\LeaseImport\Transformer\TransformerFactory
        public: false
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@monolog.logger.lease_import'
            - '%import.lease.transformer.custom_paths%'
        calls:
            - [setCsvTransformer, ['@import.lease.transformer.csv']]
            - [addApiTransformer, ['%accounting_system.mri%', '@import.lease.transformer.mri']]

    # services
    import.property.sftp_file_manager:
        class: RentJeeves\ImportBundle\Sftp\ImportSftpFileManager
        arguments:
            - '%import.property.sftp.host%'
            - '%import.property.sftp.port%'
            - '@monolog.logger.sftp_file_manager'
            - '@sftp_client'
        calls:
            - [setKeysCredentials, ['%import.property.sftp.login%', '%import.property.sftp.publickey%', '%import.property.sftp.privatekey%']]

    import.property.manager:
        class: RentJeeves\ImportBundle\PropertyImport\ImportPropertyManager
        arguments:
            - @import.property.extractor_builder
            - @import.property.transformer_factory
            - @import.property.loader_factory
            - @monolog.logger.property_import
            - @doctrine.orm.default_entity_manager

    import.property.settings_provider:
        class: RentJeeves\ImportBundle\PropertyImport\ImportPropertySettingsProvider
        arguments:
            - @soap.client.yardi.resident_transactions
            - @monolog.logger.property_import

    import.property.extractor.mri:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\MRIExtractor
        public: false
        arguments:
            - @mri.resident_data
            - @monolog.logger.property_import

    import.property.extractor.yardi:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\YardiExtractor
        public: false
        arguments:
            - @yardi.resident_data
            - @monolog.logger.property_import

    import.property.extractor.amsi:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\AMSIExtractor
        public: false
        arguments:
            - @amsi.resident_data
            - @monolog.logger.property_import

    import.property.extractor.resman:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\ResmanExtractor
        public: false
        arguments:
            - @resman.resident_data
            - @monolog.logger.property_import

    import.property.extractor.rent_manager:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\RentManagerExtractor
        public: false
        arguments:
            - '@rent_manager.client'
            - '@monolog.logger.property_import'

    import.property.extractor.csv:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\CsvExtractor
        public: false
        arguments:
            - @reader.csv
            - '@import.property.sftp_file_manager'
            - @monolog.logger.property_import

    import.lease.extractor.resman:
        class: RentJeeves\ImportBundle\LeaseImport\Extractor\ResmanExtractor
        public: false

    import.lease.extractor.csv:
        class: RentJeeves\ImportBundle\LeaseImport\Extractor\CsvExtractor
        public: false
        arguments:
            - "@import.property.extractor.csv"

    import.property.transformer.mri:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\MRITransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.lease.transformer.mri:
        class: RentJeeves\ImportBundle\LeaseImport\Transformer\MRITransformer
        public: false

    import.property.transformer.resman:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\ResmanTransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.property.transformer.yardi:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\YardiTransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.property.transformer.amsi:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\AMSITransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.property.transformer.rent_manager:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\RentManagerTransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.lease.transformer.csv:
        class: RentJeeves\ImportBundle\LeaseImport\Transformer\CsvTransformer
        public: false
        arguments:
             - "@doctrine.orm.default_entity_manager"
             - "@monolog.logger.lease_import"

    import.property.transformer.csv:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\CsvTransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @address_lookup_service
            - @monolog.logger.property_import

    import.lease.transformer.csv:
        class: RentJeeves\ImportBundle\LeaseImport\Transformer\CsvTransformer
        public: false

    import.property.loader_factory:
        class: RentJeeves\ImportBundle\PropertyImport\Loader\LoaderFactory
        arguments:
            - @import.property.loader.mapped
            - @import.property.loader.unmapped

    import.property.loader.base:
        abstract:  true
        class: RentJeeves\ImportBundle\PropertyImport\Loader\AbstractLoader
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@property.manager"
            - "@validator"
            - "@monolog.logger.property_import"

    import.property.loader.mapped:
        class: RentJeeves\ImportBundle\PropertyImport\Loader\MappedLoader
        public: false
        parent: import.property.loader.base

    import.property.loader.unmapped:
        class: RentJeeves\ImportBundle\PropertyImport\Loader\UnmappedLoader
        public: false
        parent: import.property.loader.base
