parameters:
    # using a path that leads into the project does not make sense. Use a path out of project if you need to.
    # Otherwise put transformers into ImportBundle.
    import.property.transformer.custom_paths: []

services:
    import_transformer.repository:
        class: RentJeeves\DataBundle\Entity\ImportTransformerRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - RentJeeves\DataBundle\Entity\ImportTransformer

    # factories
    import.property.extractor_factory:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\ExtractorFactory
        arguments:
            -
              %accounting_system.mri%: @import.property.extractor.mri
              %accounting_system.resman%: @import.property.extractor.resman
              %accounting_system.yardi%: @import.property.extractor.yardi
              %accounting_system.amsi%: @import.property.extractor.amsi

    import.property.transformer_factory:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\TransformerFactory
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import
            - %import.property.transformer.custom_paths%
            -
              %accounting_system.mri%: @import.property.transformer.mri
              %accounting_system.yardi%: @import.property.transformer.yardi
              %accounting_system.resman%: @import.property.transformer.resman

    # services
    import.property.manager:
        class: RentJeeves\ImportBundle\PropertyImport\ImportPropertyManager
        arguments:
            - @import.property.extractor_factory
            - @import.property.transformer_factory
            - @import.property.loader
            - @monolog.logger.property_import

    import.property.settings_provider:
        class: RentJeeves\ImportBundle\PropertyImport\ImportPropertySettingsProvider
        arguments:
            - @soap.client.yardi.resident_transactions
            - @monolog.logger.property_import

    import.property.extractor.mri:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\MRIExtractor
        public: false
        arguments:
            - @mri.resident_data
            - @monolog.logger.property_import

    import.property.extractor.yardi:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\YardiExtractor
        public: false
        arguments:
            - @yardi.resident_data
            - @monolog.logger.property_import

    import.property.extractor.amsi:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\AMSIExtractor
        public: false
        arguments:
            - @amsi.resident_data
            - @monolog.logger.property_import

    import.property.extractor.resman:
        class: RentJeeves\ImportBundle\PropertyImport\Extractor\ResmanExtractor
        public: false
        arguments:
            - @resman.resident_data
            - @monolog.logger.property_import

    import.property.transformer.mri:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\MRITransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.property.transformer.resman:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\ResmanTransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.property.transformer.yardi:
        class: RentJeeves\ImportBundle\PropertyImport\Transformer\YardiTransformer
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @monolog.logger.property_import

    import.property.loader:
        class: RentJeeves\ImportBundle\PropertyImport\Loader\PropertyLoader
        public: false
        arguments:
            - @doctrine.orm.default_entity_manager
            - @property.manager
            - @validator
            - @monolog.logger.property_import
