parameters:
    data.event_listener.doctrine.class: CreditJeeves\DataBundle\EventListener\DoctrineListener

services:
    data.event_listener.doctrine:
        class: "%data.event_listener.doctrine.class%"
        tags:
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }

