<?php

namespace CreditJeeves\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    /**
     * @param $userId
     * @return mixed
     */
    public function resetDefaults($userId)
    {
        return $this->createQueryBuilder('a')
            ->update()
            ->set('a.isDefault', '?1')
            ->where('a.userId = ?2')
            ->setParameter(1, 0)
            ->setParameter(2, $userId)
            ->getQuery()
            ->execute();
    }
}
